<?php

declare(strict_types=1);

/*
 * This file is part of the package stefanfroemken/ext-kickstarter.
 *
 * For the full copyright and license information, please read the
 * LICENSE file that was distributed with this source code.
 */

namespace StefanFroemken\ExtKickstarter\Builder;

use StefanFroemken\ExtKickstarter\Model\Graph;
use StefanFroemken\ExtKickstarter\Model\Node\Typo3\ExtensionNode;

/**
 * Get file content for .gitignore
 */
class GitIgnoreBuilder implements BuilderInterface
{
    public function build(Graph $graph, string $extPath): void
    {
        file_put_contents(
            $extPath . '.gitignore',
            $this->getFileContent($graph->getExtensionNode())
        );
    }

    private function getFileContent(ExtensionNode $extensionNode): string
    {
        return str_replace(
            [
                '{{EXTENSION_KEY}}',
            ],
            [
                $extensionNode->getExtensionKey(),
            ],
            $this->getTemplate()
        );
    }

    private function getTemplate(): string
    {
        return <<<'EOT'
########################
# {{EXTENSION_KEY}}
# global ignore file
########################
#
# Don't ignore .rej and .orig as we want to see/clean files after conflict resolution.
#
# For local exclude patterns please edit .git/info/exclude.
#
########################
#
# Ignore temporary files (left by editors and OS)
*~
*.bak
*.swp
.DS_Store
#
# Ignore by common IDEs used directories/files
nbproject
*.idea
*.project
*.vscode
.buildpath
.settings
.TemporaryItems
.webprj
.fleet
#
# Temporary files and folders
/.cache
.php_cs.cache
.php-cs-fixer.cache
.sass-cache
.session
*.log
#
# Ignore build stuff
/.ddev/*
/Build/.auth
/Build/.cache
/Build/phpunit/FunctionalTests-Job-*
/Build/bower_components/*
/Build/node_modules/*
/Build/JavaScript
!/Build/typings/no-def*
/Build/testing-docker/local/.env
/Build/testing-docker/local/macos_passwd
/typo3/sysext/*/Resources/Private/TypeScript/*.js
/typo3/sysext/*/Resources/Public/JavaScript/*.js.map
/typo3/sysext/core/Tests/AcceptanceTests-Job-*
#
# TypeScript stuff
.baseDir.ts
.tscache
#
# Ignore composer stuff
/bin/*
/vendor/*
/index.php
/typo3/install.php
#
# Ignore common TYPO3 CMS files/directories
/typo3temp/*
/typo3conf/*
!/typo3conf/ext
/typo3conf/ext/*
/fileadmin/*
/uploads/*
/FIRST_INSTALL
#
# root .htaccess file
/.htaccess
# Ignore files generated by tests
typo3/sysext/core/Tests/Acceptance/Support/_generated/
/favicon.ico
# Ignore files generated by docs rendering
Documentation-GENERATED-temp/
EOT;
    }
}